apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: starter
  annotations:
    github.com/project-slug: evelyn0410/starter
spec:
  type: other
  lifecycle: experimental
  owner: user:guest
