apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: starter
  annotations:
    github.com/project-slug: evelyn0410/starter
    backstage.io/managed-by-location: url:https://github.com/evelyn0410/starter/blob/main/catalog-info.yaml
    jenkins.io/job-full-name: admin:starter
  links:
    - url: https://github.com/evelyn0410/starter
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
