apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev                 # skaffold 실행시 -p로 정의된 profile
    build:
      insecureRegistries:
        - 192.168.41.50:5000
      local:
        push: true  # false는 로컬 테스트
      artifacts:
        - image: 192.168.41.50:5000/starter # on dev server (docker hub에 push하고 실행)
          jib:
            args:
              - -DskipTests
              - -DsendCredentialsOverHttp=true
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev -Djib.allowInsecureRegistries=true"
            fromImage: openjdk:17-jdk-slim
    deploy:
      kustomize:
        paths:
          - k8s/k3s