apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: dev                
    build:
      local:
        push: true
      artifacts:
        - image: docker.openmsa.monster/starter
          jib:
            args:
              - -DskipTests
            fromImage: openjdk:17-jdk-slim
    deploy:
      kustomize:
        paths:
          - k8s/k3s
