###################
# local
###################
server.port: 18080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    #initialization-mode: always
    username: sa
    password:
    url: jdbc:h2:mem:starter;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    #url: jdbc:h2:~/starter;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    platform: h2
  h2:
    console:
      enabled: true
      #path: /h2-console  # H2 Console의 Path
  redis:
    host: host.docker.internal
    port: 6001


logging:
  config: classpath:log4j2-local.xml