#--------------------------
# server
#--------------------------
server:
  shutdown: graceful  # graceful shutdown 적용
  servlet:
    encoding:
      charset: utf-8
      force: true

#--------------------------
# spring
#--------------------------
spring:
  application:
    name: starter
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 35s # graceful shutdown 유예시간 설정 (default 30s)

# cache ttl 설정 (cacheName:ttl)
custom:
  cache:

#--------------------------
# logging
#--------------------------
logging:
  level:
    #  root: debug
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
#--------------------------
# actuator
#--------------------------
management:
  endpoints:
    enabled-by-default: false # 1. Endpoint all disable
    # 3. Exclude all endpoint for JMX and Expose specific endpoints
    web.exposure.include: "health,info"
    jmx.exposure.exclude: "*"
  # 2. Enable specific endpoints
  endpoint:
    info.enabled: true
    health:
      enabled: true
      probes.enabled: true
      defaults.enabled: true

