#-------------------------
# prod
# application-prod.yml
#-------------------------
spring:
  #-------------------------
  # spring.datasource
  #-------------------------
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/hanexdb
    driverClassName: org.postgresql.Driver
    username: hanex
    password: hanex1234
  #-------------------------
  # REDIS (spring.redis)
  #-------------------------
  redis:
    cluster:
      mode: true
      # 6379 : master , 6380 slave
      nodes: redis-service.redis:6379,redis-service.redis:6380
      max-redirect: 3
